"""Initial schema - blogs and categories

Revision ID: 68fd405bc8c7
Revises: 
Create Date: 2026-02-10 11:03:08.379972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68fd405bc8c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('blogs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogs_category_id'), 'blogs', ['category_id'], unique=False)
    op.create_index(op.f('ix_blogs_created_at'), 'blogs', ['created_at'], unique=False)
    op.create_index(op.f('ix_blogs_published'), 'blogs', ['published'], unique=False)
    op.create_index(op.f('ix_blogs_slug'), 'blogs', ['slug'], unique=True)
    op.drop_index('idx_logi_cln2', table_name='logi')
    op.drop_table('logi')
    op.drop_index('idx_audit_log_created_at', table_name='audit_log')
    op.drop_index('idx_audit_log_use1', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_issues_l4p1', table_name='issues')
    op.drop_index('idx_issues_status', table_name='issues')
    op.drop_table('issues')
    op.drop_index('idx_abut_l4p1', table_name='abut')
    op.drop_table('abut')
    op.drop_index('idx_auth_users_cln2', table_name='auth_users')
    op.drop_index('idx_auth_users_email', table_name='auth_users')
    op.drop_table('auth_users')
    op.drop_table('clnt')
    op.drop_index('idx_bptx_bpm12', table_name='bptx')
    op.drop_table('bptx')
    op.drop_index('idx_bpmn_cln2', table_name='bpmn')
    op.drop_table('bpmn')
    op.drop_index('idx_l4pr_bpm12', table_name='l4pr')
    op.drop_index('idx_l4pr_cln2_log1', table_name='l4pr')
    op.drop_index('idx_l4pr_hierarchy', table_name='l4pr')
    op.drop_table('l4pr')
    op.drop_index('idx_acss_cln2', table_name='acss')
    op.drop_index('idx_acss_level', table_name='acss')
    op.drop_index('idx_acss_use1', table_name='acss')
    op.drop_table('acss')
    op.drop_index('idx_indt_l4p1', table_name='indt')
    op.drop_table('indt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indt',
    sa.Column('indt_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('l4p1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bpt16', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('io_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('io_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('io_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("io_type = ANY (ARRAY['input'::text, 'output'::text])", name='indt_io_type_check'),
    sa.ForeignKeyConstraint(['bpt16'], ['bptx.bpt16'], name='indt_bpt16_fkey'),
    sa.ForeignKeyConstraint(['l4p1'], ['l4pr.l4p1'], name='indt_l4p1_fkey'),
    sa.PrimaryKeyConstraint('indt_id', name='indt_pkey')
    )
    op.create_index('idx_indt_l4p1', 'indt', ['l4p1'], unique=False)
    op.create_table('acss',
    sa.Column('acss_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('use1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cln2', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('log1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aut2', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('l0p1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('l1p1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('l2p1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('l3p1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("aut2 = ANY (ARRAY['L0'::text, 'L1'::text, 'L2'::text, 'L3'::text, 'L4'::text])", name='acss_aut2_check'),
    sa.ForeignKeyConstraint(['cln2'], ['clnt.cln2'], name='acss_cln2_fkey'),
    sa.ForeignKeyConstraint(['log1'], ['logi.log1'], name='acss_log1_fkey'),
    sa.ForeignKeyConstraint(['use1'], ['auth_users.use1'], name='acss_use1_fkey'),
    sa.PrimaryKeyConstraint('acss_id', name='acss_pkey'),
    sa.UniqueConstraint('use1', 'cln2', 'log1', 'aut2', 'l0p1', 'l1p1', 'l2p1', 'l3p1', name='acss_use1_cln2_log1_aut2_l0p1_l1p1_l2p1_l3p1_key')
    )
    op.create_index('idx_acss_use1', 'acss', ['use1'], unique=False)
    op.create_index('idx_acss_level', 'acss', ['aut2'], unique=False)
    op.create_index('idx_acss_cln2', 'acss', ['cln2'], unique=False)
    op.create_table('l4pr',
    sa.Column('l4p1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('l4p9_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('l4p9_de', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('l4p9_fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('l4p9_es', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cln2', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('log1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('l0p1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('l1p1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('l2p1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('l3p1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bpm12', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status = ANY (ARRAY['active'::text, 'inactive'::text, 'draft'::text])", name='l4pr_status_check'),
    sa.ForeignKeyConstraint(['cln2'], ['clnt.cln2'], name='l4pr_cln2_fkey'),
    sa.ForeignKeyConstraint(['log1'], ['logi.log1'], name='l4pr_log1_fkey'),
    sa.PrimaryKeyConstraint('l4p1', name='l4pr_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_l4pr_hierarchy', 'l4pr', ['l0p1', 'l1p1', 'l2p1', 'l3p1'], unique=False)
    op.create_index('idx_l4pr_cln2_log1', 'l4pr', ['cln2', 'log1'], unique=False)
    op.create_index('idx_l4pr_bpm12', 'l4pr', ['bpm12'], unique=False)
    op.create_table('bpmn',
    sa.Column('bpm12', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cln2', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bpmn_xml', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bptx_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cln2'], ['clnt.cln2'], name='bpmn_cln2_fkey'),
    sa.PrimaryKeyConstraint('bpm12', name='bpmn_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_bpmn_cln2', 'bpmn', ['cln2'], unique=False)
    op.create_table('bptx',
    sa.Column('bpt16', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bpm12', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('shape_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('shape_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('shape_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bpm12'], ['bpmn.bpm12'], name='bptx_bpm12_fkey'),
    sa.PrimaryKeyConstraint('bpt16', name='bptx_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_bptx_bpm12', 'bptx', ['bpm12'], unique=False)
    op.create_table('clnt',
    sa.Column('cln2', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cln9', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cln2', name='clnt_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('auth_users',
    sa.Column('use1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cln2', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.TEXT(), server_default=sa.text("'en'::text"), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("language = ANY (ARRAY['en'::text, 'de'::text, 'fr'::text, 'es'::text])", name='auth_users_language_check'),
    sa.ForeignKeyConstraint(['cln2'], ['clnt.cln2'], name='auth_users_cln2_fkey'),
    sa.PrimaryKeyConstraint('use1', name='auth_users_pkey'),
    sa.UniqueConstraint('user_email', name='auth_users_user_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_auth_users_email', 'auth_users', ['user_email'], unique=False)
    op.create_index('idx_auth_users_cln2', 'auth_users', ['cln2'], unique=False)
    op.create_table('abut',
    sa.Column('abut_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('l4p1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bpt16', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('video_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('video_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('storage_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bpt16'], ['bptx.bpt16'], name='abut_bpt16_fkey'),
    sa.ForeignKeyConstraint(['l4p1'], ['l4pr.l4p1'], name='abut_l4p1_fkey'),
    sa.PrimaryKeyConstraint('abut_id', name='abut_pkey')
    )
    op.create_index('idx_abut_l4p1', 'abut', ['l4p1'], unique=False)
    op.create_table('issues',
    sa.Column('issue_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('l4p1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bpt16', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('issue_title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('issue_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'open'::text"), autoincrement=False, nullable=True),
    sa.Column('priority', sa.TEXT(), server_default=sa.text("'medium'::text"), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])", name='issues_priority_check'),
    sa.CheckConstraint("status = ANY (ARRAY['open'::text, 'in_progress'::text, 'resolved'::text, 'closed'::text])", name='issues_status_check'),
    sa.ForeignKeyConstraint(['bpt16'], ['bptx.bpt16'], name='issues_bpt16_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['auth_users.use1'], name='issues_created_by_fkey'),
    sa.ForeignKeyConstraint(['l4p1'], ['l4pr.l4p1'], name='issues_l4p1_fkey'),
    sa.PrimaryKeyConstraint('issue_id', name='issues_pkey')
    )
    op.create_index('idx_issues_status', 'issues', ['status'], unique=False)
    op.create_index('idx_issues_l4p1', 'issues', ['l4p1'], unique=False)
    op.create_table('audit_log',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('use1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cln2', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('log_id', name='audit_log_pkey')
    )
    op.create_index('idx_audit_log_use1', 'audit_log', ['use1'], unique=False)
    op.create_index('idx_audit_log_created_at', 'audit_log', [sa.text('created_at DESC')], unique=False)
    op.create_table('logi',
    sa.Column('log1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('log9', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cln2', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cln2'], ['clnt.cln2'], name='logi_cln2_fkey'),
    sa.PrimaryKeyConstraint('log1', name='logi_pkey')
    )
    op.create_index('idx_logi_cln2', 'logi', ['cln2'], unique=False)
    op.drop_index(op.f('ix_blogs_slug'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_published'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_created_at'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_category_id'), table_name='blogs')
    op.drop_table('blogs')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
